version: "3.9"
    
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: SXxRnc4kLLHGBnZUzWQFpqWF8seWUDcp
      MYSQL_DATABASE: joboss
      MYSQL_USER: joboss
      MYSQL_PASSWORD: dqQtJhKvqPg4zNWy
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - 3306:3306
  scripts:
    depends_on:
      - db
    build: .
    volumes:
      - scripts:/scripts
    environment:
      DB_HOST: db
      DB_USER: joboss
      DB_PASSWORD: dqQtJhKvqPg4zNWy
      DB_NAME: joboss
  backend:
    depends_on:
      - scripts
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - backend:/backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  db_data: {}
  scripts: {}
  backend: {}
